/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminSystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class PanelRiwayat extends javax.swing.JPanel {

 public Statement stm ;
 public Connection con ;
 public ResultSet rs ;
 public PreparedStatement prs ;
 DefaultTableModel model = null ;
 
    public PanelRiwayat() {
        initComponents();
        KoneksiAdmin kon = new KoneksiAdmin();
//        System.out.println(semua);
        jLabel1.setVisible(false);
        kon.Config();
        stm = kon.stm ;
        con = kon.con ;
        
    }
    void loadTable()  //throws SQLException
    {
        model = new DefaultTableModel();
        model.addColumn("Tanggal Transakasi");
          model.addColumn("Daftar Pesananan");
            model.addColumn("Daftar Pesanan");
              model.addColumn("Total Pesanan");
                model.addColumn("Total Harga");
        LoginPelanggan log = new LoginPelanggan();
        String usn = log.namaAkhir;
       try {
        String sqly = "select NamaMakanan , harga ,banyakBarang , AlamatTertuju , jenisPembayaran , tanggalTransaksi from  detailpenjualan where namaPembeli = ? order by tanggalTransaksi ";
        prs = con.prepareStatement(sqly);
        prs.setString(1, usn);
        rs = prs.executeQuery();
        while(rs.next())
        {
              jLabel1.setVisible(true);
            model.addRow(new Object []
            {
                rs.getString("NamaMakanan"),
                 rs.getString("harga"),
                   rs.getString("AlamatTertuju"),
                     rs.getString("jenisPembayaran"),
                       rs.getString("tanggalTransaksi"),
                   
            });
        }
       }
        catch(SQLException e)
                {
                    System.out.println(e.getMessage());
                }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("UUPS !!! ANDA BELUM MEMILIKI RIWAYAT PESANAN ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
