/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelSystemAdmin;

import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import raven.transitions.TransitionsForm;
import AdminSystem.KoneksiAdmin;
import java.awt.Color;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
public class Form3 extends TransitionsForm {

   public Statement stm ;
   public Connection con;
   public PreparedStatement prs ;
   public ResultSet rs ;
   DefaultTableModel model = null ;
   File f = null ;
    String path = null ;
    private ImageIcon imgicon = null ;
    String fname = null ;
    int s = 1 ;
    byte [] pimage = null ;
    public String gambarGanti  ;
    public Form3() {
        initComponents();
        KoneksiAdmin kon = new KoneksiAdmin();
          kon.Config();
        stm = kon.stm ;
        con = kon.con ;
        LoadTable();
    }
     private void LoadTable()
    {
               model = new DefaultTableModel();
//        model.addColumn("No");
        model.addColumn("idBarang");
        model.addColumn("Nama Pangan");
        model.addColumn("Harga Pangan");
        model.addColumn("Stok Pangan");
        model.addColumn("Jenis Pangan");
//        model.addColumn("Status Peminjaman ");
        try{
            int no = 0 ;
            String s = "select idBarang , namaBarang , hargaBarang ,stoBarang , jenisBarang from barang order by idBarang " ;
            rs = stm.executeQuery(s);  
            while(rs.next()){
                model.addRow(new Object[]{
//                    ++no ,
                    rs.getString(1),
                    rs.getString(2),
                    "Rp. " +rs.getString(3),
                    rs.getString(4),
//                    rs.getInt(5),
                    rs.getString(5)
                
                });
            }
            tblbarang.setModel(model);
        } catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaMakanan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hargaMakanan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        stokMakanan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jenisMakanan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        myButton1 = new button.MyButton();
        jButton1 = new button.MyButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        namaMakan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hargaMakan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        stokMakan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        myButton2 = new button.MyButton();
        jButton2 = new button.MyButton();
        jLabel1 = new javax.swing.JLabel();
        myButton3 = new button.MyButton();
        jPanel1 = new javax.swing.JPanel();
        gambar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbarang = new tabledark.TableDark();
        myButton4 = new button.MyButton();
        myButton5 = new button.MyButton();
        jenismakanan = new javax.swing.JRadioButton();
        jenisminuman = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ket = new javax.swing.JTextArea();
        myButton6 = new button.MyButton();

        jLabel5.setText("HARGA");

        jLabel6.setText("STOK");

        jLabel2.setText("PILIH JENIS");

        jenisMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUPER", "MAKANAN", "MINUMAN", " " }));

        jLabel3.setText("NAMA :");

        myButton1.setText("Tambah Data");
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        jButton1.setText("Edit Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        namaMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaMakanActionPerformed(evt);
            }
        });

        jLabel7.setText("HARGA");

        jLabel8.setText("STOK");

        jLabel4.setText("PILIH JENIS");

        jLabel9.setText("NAMA :");

        myButton2.setText("Tambah Data");
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jLabel1.setText("FORM DATA BARANG");

        myButton3.setText("Hapus Data");
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gambar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gambar, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbarang);

        myButton4.setText("Ganti Gambar");
        myButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton4ActionPerformed(evt);
            }
        });

        myButton5.setText("Terapkan Gambar");
        myButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jenismakanan);
        jenismakanan.setText("Makanan");

        buttonGroup1.add(jenisminuman);
        jenisminuman.setText("Minuman");

        jLabel10.setText("KETERANGAN");

        ket.setColumns(20);
        ket.setRows(5);
        jScrollPane2.setViewportView(ket);

        myButton6.setText("Terapkan Gambar");
        myButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stokMakan)
                            .addComponent(hargaMakan)
                            .addComponent(namaMakan)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jenismakanan)
                            .addComponent(jenisminuman)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(myButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jenismakanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jenisminuman)
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(namaMakan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(hargaMakan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(stokMakan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(myButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(myButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(myButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        try {
            String sqly = "INSERT INTO barang (namaBarang , hargaBarang , stoBarang , jenisBarang) VALUES (?,?,?,?) ";
            prs = con.prepareStatement(sqly);
            prs.setString(1, namaMakanan.getText());
            prs.setString(2, hargaMakanan.getText());
            prs.setString(3, stokMakanan.getText());
            prs.setString(4, jenisMakanan.getSelectedItem().toString());
            prs.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
        } catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }
        LoadTable();
    }//GEN-LAST:event_myButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        try {
            String sqly = "INSERT INTO barang (namaBarang , hargaBarang , stoBarang , jenisBarang) VALUES (?,?,?,?) ";
            prs = con.prepareStatement(sqly);
            prs.setString(1, namaMakan.getText());
            prs.setInt(2, Integer.parseInt(hargaMakan.getText()));
            prs.setInt(3, Integer.parseInt(stokMakan.getText()));
            String s= jenisMakanan.getSelectedItem().toString();
            String sk = "default";
           if(jenismakanan.isSelected())
            {
                sk = "MAKANAN";
            } else  if(jenisminuman.isSelected())
            {
                sk = "MINUMAN";
            }
            prs.setString(4,sk);
            prs.executeUpdate();
            System.out.println(s);
            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
        } catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }
        LoadTable();
    }//GEN-LAST:event_myButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
           
            String sqlk = "UPDATE BARANG SET namaBarang = ? , stoBarang = ? , hargaBarang = ? , jenisBarang = ? , keteranganBarang = ?  WHERE idBarang = ?";
            prs = con.prepareStatement(sqlk);
            prs.setString(1, namaMakan.getText());
            prs.setString(2,stokMakan.getText());
            prs.setString(3, hargaMakan.getText());
                       String sk = "default";
//          String sk = "default";
//            if(jenissuper.isSelected())
//            {
//                sk = "SUPER";
if(jenismakanan.isSelected())
            {
                sk = "MAKANAN";
            } else  if(jenisminuman.isSelected())
            {
                sk = "MINUMAN";
            }
            prs.setString(4, sk);
             prs.setString(5, ket.getText());
            prs.setString(6, model.getValueAt(tblbarang.getSelectedRow(), 0).toString()); //model.getValueAt(tblbarang.getSelectedRow(), 0).toString()
            prs.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil di Upload");
        }catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }
            LoadTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void myButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton4ActionPerformed
        // TODO add your handling code here:
           JFileChooser pilih = new JFileChooser();
      FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG JPEG AND JPG" ,"png" , "jpg" , "jpeg");
      pilih.addChoosableFileFilter(filter);
      int Load = pilih.showOpenDialog(null);
      
      if(Load==pilih.APPROVE_OPTION)
      {
          f = pilih.getSelectedFile();
          path = f.getAbsolutePath();
//          gam.setText(path);
          ImageIcon ii = new ImageIcon(path);
          Image img = ii.getImage().getScaledInstance(gambar.getWidth(), gambar.getHeight(), Image.SCALE_SMOOTH);
          gambar.setIcon(new ImageIcon(img));
      }
    }//GEN-LAST:event_myButton4ActionPerformed

    private void tblbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbarangMouseClicked
        // TODO add your handling code here:
        namaMakan.setText(model.getValueAt(tblbarang.getSelectedRow(), 1).toString());
        stokMakan.setText(model.getValueAt(tblbarang.getSelectedRow(), 3).toString());
        String hargam = model.getValueAt(tblbarang.getSelectedRow(), 2).toString().substring(4);
                hargaMakan.setText(hargam); //model.getValueAt(tblbarang.getSelectedRow(), 2).toString()
                gambarGanti = model.getValueAt(tblbarang.getSelectedRow(), 0).toString();
                 try {
           // TODO add your handling code here:
           prs = con.prepareStatement("SELECT gambarBarang , keteranganBarang FROM barang WHERE idBarang = ?");
           
           prs.setString(1, model.getValueAt(tblbarang.getSelectedRow(), 0).toString());
           rs = prs.executeQuery();
           if(rs.next())
           {
                ket.setText(rs.getString("keteranganBarang"));
                System.out.println("ada");
                byte [] imageData = rs.getBytes("gambarBarang");
                System.out.println("gambar " +imageData);
                if (rs.getBytes("gambarBarang")== null) {
           gambar.setBackground(Color.yellow); // set it to empty string as you desire.
           } 
                
                if(imageData==null)
                {
                     gambar.setBackground(Color.yellow);
                }
                imgicon = new ImageIcon(imageData);
                Image mm = imgicon.getImage();
                Image mm2 = mm.getScaledInstance(gambar.getWidth(), gambar.getHeight(), Image.SCALE_SMOOTH);
                
               gambar.setIcon(new ImageIcon(mm2));
           } else if (!rs.next())
           {
               gambar.setBackground(Color.yellow);
           }
           
       } catch (SQLException ex) {
//          
System.out.println(ex.getMessage());
       }
    }//GEN-LAST:event_tblbarangMouseClicked

    private void myButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton5ActionPerformed
        // TODO add your handling code here:
              InputStream is = null;
            System.out.println("Image Path" +path);
            File f = new File(path);
//            String s = makanan.getText();
//            int harga1 = Integer.parseInt(harga.getText());
//            int stok1 = Integer.parseInt(stok.getText());
        try {
            is = new FileInputStream(f);
            try {
            String sql = "UPDATE barang SET  gambarBarang = ?  WHERE idBarang = ? ";
            PreparedStatement prs;
             prs = con.prepareStatement(sql);
//             prs.setString(1, s);
//             prs.setInt(2, harga1);
//             prs.setInt(3, stok1);
             prs.setBlob(1, is);
             prs.setString(2, gambarGanti);
             
             int inserted = prs.executeUpdate();
             if(inserted> 0)
             {
                 JOptionPane.showMessageDialog(this, "Gambar Berhasil Diupload");
             }
            } catch (SQLException ex) {
//                Logger.getLogger(TabelPenjualan.class.getName()).log(Level.SEVERE, null, ex);
            }
//            prs.setString(1, s);
            
        } catch (FileNotFoundException ex ) {
//            Logger.getLogger(TabelPenjualan.class.getName()).log(Level.SEVERE, null, ex);
         
        } finally {
            try {
                is.close();
            } catch (IOException ex) {
//                Logger.getLogger(TabelPenjualan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_myButton5ActionPerformed

    private void namaMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaMakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaMakanActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton3ActionPerformed

    private void myButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel gambar;
    private javax.swing.JTextField hargaMakan;
    private javax.swing.JTextField hargaMakanan;
    private button.MyButton jButton1;
    private button.MyButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenisMakanan;
    private javax.swing.JRadioButton jenismakanan;
    private javax.swing.JRadioButton jenisminuman;
    private javax.swing.JTextArea ket;
    private button.MyButton myButton1;
    private button.MyButton myButton2;
    private button.MyButton myButton3;
    private button.MyButton myButton4;
    private button.MyButton myButton5;
    private button.MyButton myButton6;
    private javax.swing.JTextField namaMakan;
    private javax.swing.JTextField namaMakanan;
    private javax.swing.JTextField stokMakan;
    private javax.swing.JTextField stokMakanan;
    private tabledark.TableDark tblbarang;
    // End of variables declaration//GEN-END:variables
}
